# Generated by Django 5.1.3 on 2024-11-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='code',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
